base_path: ./dataset/Baron/data.h5
save_path: ./result/Baron/log_Baron.txt
highly_genes: 2000
seed: 1
graph_type: KNN
graph_distance_cutoff_num_stds: 0.0
pretrain_epochs: 1000
epochs: 200
learning_rate: 0.00005
lambd: 0.0001
dim: 256
hidden_dim: 64
adj_dim: 32
eval_metric:
  - nmi
  - ari
cluster_type: spectral